version: '3'

services:
  main:
    environment:
      - TZ=Asia/Seoul
    image: siyoun/hackerton2024-server:latest
    command: pnpm start:prod
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:16
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
      - TZ=Asia/Seoul
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  db-data:
