version: '3'

services:
  hackerton:
    build: .
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace/hackerton-2024
    command: sleep infinity
    depends_on:
      - hackerton-database

  hackerton-database:
    image: postgres:16
    container_name: hackerton-database
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Seoul
    volumes:
      - hackerton-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  hackerton-db: