name: CI Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Login Dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build the Docker image
          run: docker build -t hackerton-server ./app/
        - name: taging
          run: docker tag hackerton-server:latest siyoun/hackerton-server:latest
        - name: Push to Dockerhub
          run: docker push siyoun/hackerton-server:latest