name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Pull Docker image
        run: sudo docker pull siyoun/hackerton2024-server:latest
      - name: Delete Old docker container
        run: cd ./app && sudo docker compose down --rmi all
      - name: Run Docker Container
        run: cd ./app && sudo docker compose up -d
