name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull siyoun/gaeboptoday-server:latest
      - name: Delete Old docker container
        run: docker compose down --rmi all
      - name: Run Docker Container
        run: docker compose up -d
